-- AlterTable
ALTER TABLE "Metric" ADD COLUMN     "adId" TEXT,
ADD COLUMN     "costPerAddToCart" DOUBLE PRECISION;

-- AddForeignKey
ALTER TABLE "Metric" ADD CONSTRAINT "Metric_adId_fkey" FOREIGN KEY ("adId") REFERENCES "Ad"("id") ON DELETE SET NULL ON UPDATE CASCADE;
