"""Schemas for the Creative Agent (PRD.md build step 6)."""

from datetime import datetime
from typing import Literal

from pydantic import Field

from app.schemas.base import CamelCaseModel

CtaType = Literal[
    "SHOP_NOW",
    "LEARN_MORE",
    "SIGN_UP",
    "SUBSCRIBE",
    "CONTACT_US",
    "MESSAGE_PAGE",
    "GET_OFFER",
    "DOWNLOAD",
    "BOOK_NOW",
]

CreativeStatus = Literal["GENERATED", "SELECTED", "REJECTED"]

_VARIANT_COUNT = 4


class GeneratedCreativeVariant(CamelCaseModel):
    """One ad creative variant, as generated by the LLM.

    Field names mirror Meta's own ad creative terminology (see
    app/services/creative.py and the Creative model's doc comment) — this
    is what the tool call must produce, one row per variant.
    """

    headline: str
    body_text: str
    description: str
    cta: CtaType
    creative_angle: str
    image_prompt: str
    video_prompt: str


class GeneratedCreativeBatch(CamelCaseModel):
    """The full tool-call payload: exactly _VARIANT_COUNT variants (A-D)."""

    variants: list[GeneratedCreativeVariant] = Field(
        min_length=_VARIANT_COUNT, max_length=_VARIANT_COUNT
    )


class CreativeResponse(CamelCaseModel):
    """Public-facing representation of a stored Creative."""

    id: str
    campaign_id: str
    ad_id: str | None
    headline: str
    body_text: str
    description: str
    cta: CtaType
    creative_angle: str | None
    image_prompt: str | None
    video_prompt: str | None
    status: CreativeStatus
    created_at: datetime
