import { Link } from 'react-router-dom'

// DRAFT — pending legal review. Content is grounded in what the app
// actually does as of 2026-09-19, but the legal language itself
// (liability, fees, governing law, the bracketed placeholders below) has
// not been reviewed by counsel and should not be treated as final until
// it is.
export function TermsOfServicePage() {
  return (
    <main className="legal-page">
      <h1>Terms of Service</h1>
      <p>Last updated: September 19, 2026</p>

      <h2>1. Acceptance of these terms</h2>
      <p>
        By creating an account or using Sales Guru, you agree to these terms.
        If you don't agree, don't use the service.
      </p>

      <h2>2. What Sales Guru does</h2>
      <p>
        Sales Guru generates ad strategy, ad copy, and ad creative using AI,
        and — only after you explicitly approve a specific campaign — publishes
        it to Meta Ads using the Meta Marketing API, on your behalf.
      </p>

      <h2>3. Your account</h2>
      <p>
        You're responsible for the accuracy of the business and product
        information you provide, for keeping your login credentials secure,
        and for having the actual authority to advertise on behalf of any
        business you connect.
      </p>

      <h2>4. Connecting Meta Ads</h2>
      <p>
        When you connect a Meta ad account and Page, you authorize Sales Guru
        to act on that ad account within the permissions you grant. Data
        obtained through that connection is used only to create, manage, and
        report on advertising campaigns for your own business — never sold,
        never used to target anyone else, and never shared beyond the
        service providers named in our{' '}
        <Link to="/privacy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </Link>
        . You remain responsible for your own compliance with Meta's
        Advertising Policies and Meta's own Terms of Service. Advertising
        spend is billed directly by Meta to the payment method on your Meta
        ad account — Sales Guru does not collect or process ad spend itself.
      </p>

      <h2>5. AI-generated content</h2>
      <p>
        Ad strategy, copy, and creative are generated by AI and may contain
        errors or inaccuracies. Nothing is published to Meta until you review
        it and take the explicit "Approve &amp; Publish" action — you are
        responsible for reviewing generated content before approving it.
      </p>

      <h2>6. Acceptable use</h2>
      <ul>
        <li>
          Only upload photos and content you own or have the rights to use in
          advertising.
        </li>
        <li>
          Don't use Sales Guru to create unlawful, infringing, or deceptive
          advertising.
        </li>
        <li>
          Comply with Meta's Advertising Policies for anything published
          through your connected account.
        </li>
      </ul>

      <h2>7. Fees</h2>
      <p>
        <strong>
          [Placeholder — pricing/fees for using Sales Guru itself are not yet
          finalized.]
        </strong>{' '}
        Any advertising spend is separate from Sales Guru's own fees (if any)
        and is billed directly by Meta.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        Sales Guru is provided "as is." We don't guarantee any particular
        advertising results, performance, or return on ad spend.{' '}
        <strong>
          [Placeholder — full limitation-of-liability language pending legal
          review.]
        </strong>
      </p>

      <h2>9. Termination</h2>
      <p>
        You can disconnect your Meta account or stop using Sales Guru at any
        time. We may suspend or terminate an account that violates these
        terms.
      </p>

      <h2>10. Governing law</h2>
      <p>
        <strong>[Placeholder — governing law and jurisdiction pending legal
        review.]</strong>
      </p>

      <h2>11. Changes to these terms</h2>
      <p>
        We may update these terms as Sales Guru changes. We'll update the
        "Last updated" date above when we do.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these terms: <strong>[legal@salesguru.app]</strong>
      </p>
    </main>
  )
}
